// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI (introspección / db execute / DDL): usa la conexión DIRECTA de Neon
    // (sin PgBouncer). La integración de Neon en Vercel expone
    // DATABASE_URL_UNPOOLED; si no existe, cae a la pooled DATABASE_URL.
    url: process.env["DATABASE_URL_UNPOOLED"] ?? process.env["DATABASE_URL"],
  },
});
